# LambdaTest Configuration

# Project and folder configuration
project_id: "01KTZWQCMPWY7P5QV445SWRT5E"
folder_id: "01KTZWQD60HFFKXZ6MZ3VRSQQ8"

# Test Run configuration
assignee: 3337417

# Test URL for automation
# test_url: "https://github.com/alphy2022/kaneai-demo"
